<RoundButton@MDCard>:
    size_hint: None, None
    size: "200dp", "200dp"
    radius: [100, 100, 100, 100]
    md_bg_color: app.theme_cls.primary_color
    ripple_behavior: True
    elevation: 2
    text: ""
    MDLabel:
        text: root.text  # o label pega o text do widget
        halign: "center"
        pos_hint: {"center_y": .5}
        font_name: app.font_name
        font_size: "24sp"
        theme_text_color: "Custom"
        text_color: 1,1,1,1